spring:
  datasource:
    url: jdbc:mysql://umc-db.czid81mmuxlk.ap-northeast-2.rds.amazonaws.com:3306/MyDB?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username : admin
    password : mypassword!
#    url: jdbc:mysql://localhost:3306/my_insider?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: 0000



  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      force-response: true


